kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: edx-mgmtui
  namespace: easl-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edx-mgmtui
  template:
    metadata:
      labels:
        app: edx-mgmtui
    spec:
      hostAliases:
      - ip: "10.7.0.20"
        hostnames:
        - "prodceph.easltech.com"
      containers:
        - name: edx-mgmtui
          image: ghcr.io/easltech/edx-mgmtui:v3.2.1.1
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: PdxAppName
              value: edx-mgmtui
            - name: PdxAppType
              value: mgmt
            - name: PdxDbApiAddress
              value: http://database-api
            - name: PdxLogApiAddress
              value: http://logging-api/Log
            - name: PdxLogFilepath
              value: /app/log/edx-mgmtui-.log
            - name: PdxLogExclusionExpression
              value: (StartsWith(SourceContext, 'System.Net.Http.HttpClient.') or StartsWith(SourceContext, 'Serilog.') or StartsWith(SourceContext, 'Microsoft.')) and @l = 'Information'
            - name: PdxNodeName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: PdxPodName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: PdxNamespace
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PdxPodIP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
            limits:
              cpu: '8'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 512Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
