kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: edx-transformer
  namespace: easl-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edx-transformer
  template:
    metadata:
      labels:
        app: edx-transformer
    spec:
      hostAliases:
      - ip: "10.7.0.20"
        hostnames:
        - "prodceph.easltech.com"
      containers:
        - name: edx-transformer
          image: ghcr.io/easltech/edx-transformer:v3.1.0
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: PdxAppName
              value: edx-transformer
            - name: PdxAppType
              value: edx
            - name: PdxDbApiAddress
              value: http://database-api
            - name: PdxLogApiAddress
              value: http://logging-api/Log
            - name: PdxConfigLogUpdate
              value: 'true'
            - name: PdxLogFilepath
              value: /app/log/edx-transformer-.log
            - name: PdxLogExclusionExpression
              value: (StartsWith(SourceContext, 'System.Net.Http.HttpClient.') or StartsWith(SourceContext, 'Serilog.') or StartsWith(SourceContext, 'Microsoft.')) and @l = 'Information'
            - name: PdxNodeName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: PdxPodName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: PdxNamespace
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PdxPodIP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
            limits:
              cpu: '4'
              memory: 8Gi
            requests:
              cpu: '1'
              memory: 4Gi
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /_health
              port: 5000
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 900
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
