kind: Deployment
apiVersion: apps/v1
metadata:
  name: mock-data-file-stream
  namespace: easl-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-data-file-stream
  template:
    metadata:
      labels:
        app: mock-data-file-stream
    spec:
      containers:
        - name: mock-data-file-stream
          image: ghcr.io/easltech/mock-data-file-stream:v1.0.1-dev.7
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: PdxAppName
              value: mock-data-file-stream
            - name: PdxAppType
              value: edx
            - name: PdxClientGroup
              value: easl-demo
            - name: PdxDbApiAddress
              value: http://database-api
            - name: PdxLogApiAddress
              value: http://logging-api/Log
            - name: PdxConfigLogUpdate
              value: 'false'
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 256Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred