
kind: Service
apiVersion: v1
metadata:
  name: auth-api
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: auth-api
  type: ClusterIP