kind: Service
apiVersion: v1
metadata:
  name: edx-mgmtui
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: edx-mgmtui
  type: LoadBalancer
  loadBalancerIP: 10.10.1.59