kind: Deployment
apiVersion: apps/v1
metadata:
  name: forian-control-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forian-control-api
  template:
    metadata:
      labels:
        app: forian-control-api
    spec:
      containers:
        - name: forian-control-api
          image: ghcr.io/phoeniqstech/forian-control-api:v0.0.4
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: PdxAppName
              value: control-api
            - name: PdxAppType
              value: forian
            - name: PdxClientGroup
              value: default
            - name: PdxLogApiAddress
              value: http://logging-api:6060/Log


            - name: AppSettings__LogLevel
              value: Information
            - name: AppSettings__S3Address
              value: "minio-system-1.minio"
            - name: AppSettings__S3AccessKey
              value: devuser
            - name: AppSettings__S3SecretKey
              value: phoeniqsDev01

            - name: AppSettings__ApiKeyConfigurations__0__ApiKey
              value: "67814f7f-c2b5-43ba-8413-9aa776fc4dc1"
            - name: AppSettings__ApiKeyConfigurations__0__EncryptionKey
              value: "fQIiBk3JAHMM7ZulxUxeNliX0xrtggx0ImPNlvpFTSk="
            - name: AppSettings__ApiKeyConfigurations__0__BucketName
              value: "test-one"

            - name: AppSettings__ApiKeyConfigurations__1__ApiKey
              value: "6d44a28a-d145-41d4-a9f7-8fad66b5642b"
            - name: AppSettings__ApiKeyConfigurations__1__EncryptionKey
              value: "RgRRhIkAhxTBfu0cEZ6vDoTFDwbrSqwiWKUiSihdR9g="
            - name: AppSettings__ApiKeyConfigurations__1__BucketName
              value: "test-two"

            - name: MinioSettings__Endpoint
              value: "minio-system-1.minio"
            - name: MinioSettings__AccessKey
              value: "devuser"
            - name: MinioSettings__SecretKey
              value: "phoeniqsDev01"
            - name: MinioSettings__UsesSSL
              value: "false"
            - name: MinioSettings__Bucket
              value: "forian"

            - name: DataModel__AgentConfigurations__hoover-test__AgentWatcherConfiguration__SleepTime
              value: "00:15:00"
            - name: DataModel__AgentConfigurations__hoover-test__DatabaseConnectionString
              value: "Server=localhost:5432;Database=easltech;User Id=easltech;Password=FC3tgppqqb3h4cJ4vzwKrWtk;"
            - name: DataModel__AgentConfigurations__hoover-test__DatabaseSqlScript
              value: "SELECT * FROM public.orders ORDER BY order_id ASC"
            - name: DataModel__AgentConfigurations__hoover-test__DesiredProgramVersion
              value: "0.0.3"
            - name: DataModel__AgentConfigurations__hoover-test__CurrentProgramVersion
              value: "0.0.3"
            - name: DataModel__AgentConfigurations__hoover-test__DesiredSleepTime
              value: "01:00:00"
            - name: DataModel__AgentConfigurations__hoover-test__LastProgramStart
              value: "2022-09-06T16:18:30.7912209Z"
            - name: DataModel__AgentConfigurations__hoover-test__RebootControlFlag
              value: "false"
            - name: DataModel__AgentConfigurations__hoover-test__ApiKey
              value: "67814f7f-c2b5-43ba-8413-9aa776fc4dc1"


            - name: PdxDbServer
              value: mysql.mysql
            - name: PdxDbUser
              value: root
            - name: PdxDbPassword
              value: easlTmysql01
            - name: PdxNodeName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: PdxPodName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: PdxNamespace
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PdxPodIP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: PdxServiceAccountName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred