apiVersion: v1
kind: Service
metadata:
  name: forian-control-api-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
    - name: https
      port: 443
      targetPort: 5000
      protocol: TCP
  selector:
    app: forian-control-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forian-control-api-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: qaapi.easltech.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: forian-control-api-service
            port:
              name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: forian-control-api-secure-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  rules:
  - host: qaapi.easltech.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: forian-control-api-service
            port:
              name: http
    tls:
    - hosts:
        - qaapi.easltech.com
      secretName: easltech-cert