apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: emailsender
  namespace: leaflink
spec:
  encryptedData:
    password: AgDaFfVd7gBa3CMjMYUtImjt7v3uiErHxFhsG9GbFPBU25bCLEE+CsMafuhdUvwXBnwLxTc5AEbLEuIjXoVQwEPfS5zz06kgdgecPssvwa5bKxiz2GWXjF6Awlm5AV/b04F/t5/ahziZYsfKYf+lcExS+ePCjxkIgLRZs7PAc+rNtbsZ139RVJd4UcMVVOYauihKdfklbiYsQQP8HXJ2b58532Fo8RabXLAWJokOX/5CUaRmciGcbajphZx2AvGYHQ0JSoUfv985FMm0dRZJEarxcjbjuiSOJ0YCouKWWNlVIB4WnMsZevvtidMeq0pA0pKCuyahOO9UKb5qHjW84UM8Knpun2BsbvyC6xH9Ej7zaeg55641Fc5iqRBApj4J5UJQvjNr1umimQMCnrC719k9n4zW0VwSP4akMByc3X2QC+AhB4rIEOpAAGqFcjwNLgUOVtu/dH5KcVfmijNnZMbDXxa+akULCY+odkiCkZTohB7f4R6v5vXZV/IlIMxdFLKRKbcies49QHwRsoW5JTkfGLAstTNbt0b7e+Xoh7cGJokIXz+P4Dcz7nl5srQp+/yTuGS/v2CGLlC7RSFvEUpDa0xv3S/acKoH9EvEqYhTYMygwiFvMot92BKktAkbLPCoATurCwx7yx2BVwAg9GgdoBpiFEgOeu8JgMDCUCgw6wm8yVbhGFm8vag2IpvWsFAtJTH3CGvX9H3117e0R5Mr
  template:
    metadata:
      name: emailsender
      namespace: leaflink