kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: database-api
  namespace: leaflink
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database-api
  template:
    metadata:
      labels:
        app: database-api
    spec:
      containers:
        - name: database-api
          image: ghcr.io/phoeniqstech/database-api:v1.1.4
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: PdxDbServer
              value: mysql.mysql
            - name: PdxDbUser
              value: root
            - name: PdxDbPassword
              value: easlTmysql01
            - name: PdxLogApiAddress
              value: http://logging-api/Log
            - name: PdxClientGroup
              value: default
            - name: PdxAppType
              value: api
            - name: PdxAppName
              value: database-api
            - name: AppSettings__MaxAttemptsInLastHour
              value: "3"
            - name: AppSettings__Issuer
              value: "10.10.1.59"
            - name: AppSettings__Secret
              value: ZufvMKezd77HauKI4ge9e7VK4O8KyJyZOtdhrgn4mJGdHhSiPFWlD6M6vds8idiURdpDCiG3yqZiah68xQbYCR74DEwtiIpkMAnjerpQXklA0nnvlSv2G59BVqkip8hM
            - name: AppSettings__LogLevel
              value: Information
            - name: AppSettings__TokenLifeTime
              value: "01:00:00"
            - name: AppSettings__RefreshTokenLifeTime
              value: "06:00:00"
            - name: PdxNodeName
            - name: EmailSettings__WebHostAddress
              value: http://10.10.1.59
            - name: EmailSettings__EmailSendingAddress
              value: devops@easltech.com
            - name: EmailSettings__EmailHost
              value: smtp.gmail.com
            - name: EmailSettings__EmailSendingPassword
              value: piwbdvjapcrjhgwr
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: PdxPodName
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PdxNamespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PdxPodIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PdxServiceAccountName
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 256Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
