kind: Deployment
apiVersion: apps/v1
metadata:
  name: edx-mgmtui
  namespace: leaflink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edx-mgmtui
  template:
    metadata:
      labels:
        app: edx-mgmtui
    spec:
      containers:
        - name: edx-mgmtui
          image: ghcr.io/easltech/edx-mgmtui:v1.1.21.1
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: PdxAppName
              value: edx-mgmtui
            - name: PdxAppType
              value: mgmt
            - name: PdxClientGroup
              value: default
            - name: PdxDbApiAddress
              value: http://database-api
            - name: PdxAuthApiAddress
              value: http://auth-api
            - name: PdxLogApiAddress
              value: http://logging-api/Log
            - name: PdxConfigLogUpdate
              value: 'true'
            - name: PdxNodeName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: PdxPodName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: PdxNamespace
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PdxPodIP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: PdxServiceAccountName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
          resources:
            limits:
              cpu: '8'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 512Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
