kind: Deployment
apiVersion: apps/v1
metadata:
  name: edx-emailsender
  namespace: leaflink
spec:
  containers:
    - name: edx-emailsender
      image: ghcr.io/phoeniqstech/edx-emailsender:v1.1.9
      env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Release
        - name: PdxAppName
          value: edx-emailsender
        - name: PdxAppType
          value: edx
        - name: PdxClientGroup
          value: leaflink
        - name: PdxDbApiAddress
          value: http://database-api
        - name: PdxLogApiAddress
          value: http://logging-api/Log
        - name: PdxConfigLogUpdate
          value: 'false'
        - name: PdxNodeName
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: PdxPodName
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: PdxNamespace
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PdxPodIP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: PdxServiceAccountName
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.serviceAccountName
      resources:
        limits:
          cpu: '1'
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
  imagePullSecrets:
    - name: regcred