kind: Deployment
apiVersion: apps/v1
metadata:
  name: edx-jobdispatcher
  namespace: leaflink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edx-jobdispatcher
  template:
    metadata:
      labels:
        app: edx-jobdispatcher
    spec:
      containers:
        - name: edx-jobdispatcher
          image: ghcr.io/phoeniqstech/edx-jobdispatcher:v1.1.7
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: PdxAppName
              value: edx-jobdispatcher
            - name: PdxAppType
              value: edx
            - name: PdxClientGroup
              value: default
            - name: PdxDbApiAddress
              value: http://database-api
            - name: PdxLogApiAddress
              value: http://logging-api/Log
            - name: PdxConfigLogUpdate
              value: 'true'
            - name: PdxNodeName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: PdxPodName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: PdxNamespace
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PdxPodIP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: PdxServiceAccountName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 1Gi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
