apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-discovery-account
  namespace: leaflink
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-discovery-account
rules:
  - apiGroups: ["apps"]
    resources: ["pods","deployments"]
    verbs: ["list", "get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-discovery-account
subjects:
- kind: ServiceAccount
  name: service-discovery-account
  namespace: leaflink
roleRef:
  kind: ClusterRole
  name: service-discovery-account
  apiGroup: rbac.authorization.k8s.io
