kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: edx-filemanager
  namespace: qa-bbirdai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edx-filemanager
  template:
    metadata:
      labels:
        app: edx-filemanager
    spec:
      hostAliases:
      - ip: "10.7.0.20"
        hostnames:
        - "prodceph.easltech.com"
      containers:
        - name: edx-filemanager
          image: ghcr.io/easltech/edx-filemanager:v3.2.1.2
          env:
            - name: PdxAppName
              value: edx-filemanager
            - name: PdxAppType
              value: edx
            - name: PdxLogApiAddress
              value: http://logging-api/Log
            - name: PdxLogFilepath
              value: /app/log/edx-filemanager-.log
            - name: PdxLogExclusionExpression
              value: (StartsWith(SourceContext, 'System.Net.Http.HttpClient.') or StartsWith(SourceContext, 'Serilog.') or StartsWith(SourceContext, 'Microsoft.')) and @l = 'Information'
            - name: PdxDbApiAddress
              value: http://database-api
            - name: PdxNodeName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: PdxPodName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: PdxNamespace
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PdxPodIP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
          resources:
            limits:
              cpu: '2'
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /_health
              port: 5000
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 900
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: regcred
  updateStrategy:
    type: RollingUpdate
