kind: Service
apiVersion: v1
metadata:
  name: edx-mgmtui
  namespace: easl-azure
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: edx-mgmtui
  type: ClusterIP