kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: database-api
  namespace: bbirdai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: database-api
  template:
    metadata:
      labels:
        app: database-api
    spec:
      containers:
        - name: database-api
          image: ghcr.io/easltech/database-api:v1.3.0.1
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: http://+:5000
            - name: PdxDbServer
              value: bbirdai-mysql.bbirdai-mysql
            - name: PdxDbUser
              valueFrom:
                secretKeyRef:
                  name: dblogin
                  key: user
            - name: PdxDbPassword
              valueFrom:
                secretKeyRef:
                  name: dblogin
                  key: password
            - name: PdxLogApiAddress
              value: http://logging-api/Log
            - name: PdxClientGroup
              value: bbirdai
            - name: PdxAppType
              value: api
            - name: PdxAppName
              value: database-api
            - name: PdxNodeName
            - name: PdxNodeName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: PdxPodName
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PdxNamespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PdxPodIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PdxServiceAccountName
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 256Mi
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /_health
              port: 5000
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 900
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
