kind: Deployment
apiVersion: apps/v1
metadata:
  name: edx-transformer
  namespace: bbirdai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: edx-transformer
  template:
    metadata:
      labels:
        app: edx-transformer
    spec:
      containers:
        - name: edx-transformer
          image: ghcr.io/easltech/edx-transformer:v1.1.26-bbirdai
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: PdxAppName
              value: edx-transformer
            - name: PdxAppType
              value: edx
            - name: PdxClientGroup
              value: bbirdai
            - name: PdxDbApiAddress
              value: http://database-api
            - name: PdxLogApiAddress
              value: http://logging-api/Log
            - name: PdxConfigLogUpdate
              value: 'true'
            - name: PdxNodeName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: PdxPodName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: PdxNamespace
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PdxPodIP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: PdxServiceAccountName
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.serviceAccountName
          resources:
            limits:
              cpu: '4'
              memory: 4Gi
            requests:
              cpu: '1'
              memory: 2Gi
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /_health
              port: 5000
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 900
            successThreshold: 1
            failureThreshold: 3
      restartPolicy: Always
      serviceAccountName: bbirdai-service-discovery-account
      imagePullSecrets:
        - name: regcred
