apiVersion: apps/v1
kind: Deployment
metadata:
  name: edx-errorhandler
  namespace: bbirdai
spec:
  selector:
    matchLabels:
      app: edx-errorhandler
  template:
    metadata:
      labels:
        app: edx-errorhandler
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: edx-errorhandler
          image: ghcr.io/easltech/edx-errorhandler:v1.1.25.2
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: PdxAppName
            value: edx-errorhandler
          - name: PdxAppType
            value: edx
          - name: PdxClientGroup
            value: bbirdai
          - name: PdxDbApiAddress
            value: http://database-api
          - name: PdxLogApiAddress
            value: http://logging-api/Log
          - name: PdxConfigLogUpdate
            value: 'true'
          - name: PdxNodeName
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: PdxPodName
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: PdxNamespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: PdxPodIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: PdxServiceAccountName
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName