kind: Deployment
apiVersion: apps/v1
metadata:
  name: mock-data-api
  namespace: bbirdai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-data-api
  template:
    metadata:
      labels:
        app: mock-data-api
    spec:
      containers:
        - name: mock-data-api
          image: ghcr.io/easltech/mock-data-provider:v1.0.0
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:80
            - name: PdxAppName
              value: mock-data-api
            - name: PdxAppType
              value: edx
            - name: PdxClientGroup
              value: bbirdai
            - name: PdxDbApiAddress
              value: http://database-api
            - name: PdxLogApiAddress
              value: http://logging-api/Log
            - name: PdxConfigLogUpdate
              value: 'false'
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
            requests:
              cpu: '1'
              memory: 256Mi
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred